powerConsumption <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
powerConsumption$Date <- as.character(powerConsumption$Date)
powerConsumption$Time <- as.character(powerConsumption$Time)
powerConsumption$Time <- strptime(paste(powerConsumption$Date,powerConsumption$Time), "%d/%m/%Y %H:%M:%S")
powerConsumption$Date <- as.Date(powerConsumption$Date, format = "%d/%m/%Y")
subset <- powerConsumption[powerConsumption$Date >= "2007-02-01" & powerConsumption$Date <= "2007-02-02", ]
subset$Sub_metering_1 <- as.numeric(levels(subset$Sub_metering_1)[subset$Sub_metering_1])
subset$Sub_metering_2 <- as.numeric(levels(subset$Sub_metering_2)[subset$Sub_metering_2])
#subset$Sub_metering_3 <- as.numeric(levels(subset$Sub_metering_3)[subset$Sub_metering_3])
with(subset, plot(Time, Sub_metering_1, type = "s", col = "black", xlab = "", ylab = "Energy sub metering"))
with(subset, points(Time, Sub_metering_2, type = "s", col = "red"))
with(subset, points(Time, Sub_metering_3, type = "s", col = "blue"))
legend(cex=0.6, "topright", lty = c(1, 1, 1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))